### ISSUE TITLE
Trying to edit an unsaved graph will return an 404 not found

### ISSUE THREAD

**Issue by Darkkir** [GraphLinq/GraphLinq.IDE#1]
When you create a new graph that you didn't save before, you are unable to edit it from the graph overview.
(https://app.graphlinq.io/app/graphs) Trying to edit it by clicking on the graph will redirect you to https://ide.graphlinq.io/graphId, which displays an 404 error.

**Comment by nightwolf93** [comment]
Thank for the report
Fix in progress

**Comment by jrbgit** [comment]
> Thank for the report Fix in progress

Any update on this, or can this issue be closed?

@w0dm4n @fafifox @yamidevs @Darkkir

**Comment by jrbgit** [comment]
This no longer causes a 404. However, I believe that because the IDE attempts to restore the Graph from the local cache, it doesn't always open the graph you clicked on. I will leave this issue open.
